version: "3.9"
services:
  ai-service:
    image: ml-test
    ports:
      - "8080"
    restart: always
    networks:
      - ml

  load-balancer:
    image: nginx:latest
    volumes:
      - ./deploy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - ml
    depends_on:
      - ai-service

networks:
  ml: