version: "3.9"
services:
  redis:
    image: redis:latest
    ports:
      - "6379"
    networks:
      - ml

  ai-service:
    image: ghcr.io/xii1/ml-test:$AI_SERVICE_TAG
    volumes:
      - pre_trained:/app/pre_trained_models
    ports:
      - "8080"
    restart: always
    networks:
      - ml
    depends_on:
      - redis

  load-balancer:
    image: nginx:latest
    volumes:
      - ./deploy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - ml
    depends_on:
      - ai-service

networks:
  ml:
volumes:
  pre_trained: